export enum H_Tipo {
  SIMPLE = 'SIMPLE',
  INDIVIDUAL = 'INDIVIDUAL',
  DOBLE = 'DOBLE',
  TRIPLE = 'TRIPLE',
  CUADRUPLE = 'CUADRUPLE',
  SUITE = 'SUITE',
  DELUXE = 'DELUXE',
  ESTUDIO = 'ESTUDIO'
}
